# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vUYE3uyidUS5O6979qNOcKvvYuErHCCM
"""

import matplotlib.pyplot as plt
import numpy as np

x=np.array([1,3,5,7])
y=np.array([2,4,6,8])

plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([1,5,1,5])
x=np.array([2,2,2.25,2.50])

plt.plot(x,y)
plt.show()